// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/linkservi-pro/DashboardPro.tsx": () => import("../components/mockups/linkservi-pro/DashboardPro.tsx"),
  "./components/mockups/linkservi-pro/HeroEditorial.tsx": () => import("../components/mockups/linkservi-pro/HeroEditorial.tsx"),
  "./components/mockups/linkservi-pro/TrustFirst.tsx": () => import("../components/mockups/linkservi-pro/TrustFirst.tsx")
};
